### ISSUE TITLE
Community Understanding and Clarity of Seraphis

### ISSUE THREAD

**Issue by KewbitXMR** [UkoeHB/Seraphis#10]
This is no necessarily an 'issue' but with a background in mathematics I was able to really simplify it down int what people want to know etc.

It's already been posted on most platforms but perhaps you could link it back from the repo to help people understand it, I'm sure it will help drive your donations up for it :)

[https://kewbit.org/simplified-explanation-of-seraphis/](https://kewbit.org/simplified-explanation-of-seraphis/)

**Comment by dimalinux** [comment]
I'm guessing that was written by AI? It's misleading. It attributes base
features of Monero to Seraphis instead of describing how Seraphis proposes
to improve Monero.

**Comment by KewbitXMR** [comment]
Could you clarify which part seems to be written by AI?

I read your document, if anything is factually incorrect I will change it.

I don't think as though I'm attributing the original work to Seraphis, which makes you say that?

**Comment by KewbitXMR** [comment]
After reading again... I still can't see which part of this is wrong?

**Comment by UkoeHB** [comment]
I'll give a couple examples why this looks AI generated (i.e. a bunch of vague poorly-composed information scraped from the internet):

> In a typical transaction system, anyone could potentially see details about your finances. Seraphis changes this by hiding transaction details from outsiders.

Seraphis does not change this. Monero already hides transaction details using RingCT.

> Even if someone tries to cheat the system or double-spend (use the same money twice), Seraphis ensures it will be detected, and the system will reject fraudulent transactions.

Again, Monero already does this using cryptonote key images. It is misleading to suggest Seraphis is a breakthrough in this area.

> Seraphis makes sure that only the person with the right key (like a password) can spend that money, and it hides the amount and who’s involved in the transaction.

The analysis here and throughout is very shallow. Monero already does all of this. Seraphis only innovates in *how* transactions are constructed, enabling better proof structures and address formats.
